apiVersion: v1
kind: Pod
metadata:
  name: my-test
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: 1
  - name: wavefront
    image: telegraf:1.9
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
