apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
  labels:
    k8s-app: fluentd-agent
spec:
  type: ClusterIP
  selector:
    k8s-app: fluentd-agent
  ports:
  - name: fluentd-input
    port: 24224
    targetPort: fwd-input
    protocol: TCP
  - name: fluentd-input-udp
    port: 24224
    targetPort: fwd-input-udp
    protocol: UDP
  - name: fluentd-syslog-input
    port: 5140
    targetPort: fwd-syslog
    protocol: TCP
